
services: 
  ollama-server:
    build:
      context: .
    ports:
      - "11434:11434"
      - "8080:8080"
    volumes:
      - ./ModelStorage:/app/ModelStorage
    environment:
      - OLLAMA_HOST=http://127.0.0.1:11434
    mem_limit: 8g